package analysis.terms

val E = Const("E", Math.E)
val PI = Const("PI", Math.PI)
val zero = Num(0)
val one = Num(1)
val two = Num(2)
val three = Num(3)
val four = Num(4)
val five = Num(5)
val six = Num(6)
val seven = Num(7)
val x = Variable("x")
val y = Variable("y")
val z = Variable("z")
val q = Variable("q")